const ExhData = [
  {
    id: 1,
    image: "",
    alt: "Art Basel",
    descrip: "Daises, Miami - Featured on Timeout",
    isOn: true,
    year: "2021",
  },
  {
    id: 2,
    image: "",
    alt: "Basic Space",
    descrip: "Daises, New York City",
    isOn: false,
  },
  {
    id: 3,
    image: "",
    alt: "The Cooper Union",
    descrip: "To See Before You Wake, Solo Show, New York City",
    isOn: false,
  },
  {
    id: 4,
    image: "",
    alt: "The Cooper Union",
    descrip: "End of Year Show, New York City",
    isOn: false,
  },
  {
    id: 5,
    image: "",
    alt: "Seaport District NYC & Manual NYC",
    descrip:
      "Viewfinder, NYC - Reviewed by Jerry Salts for New York Magazine (Print)",
    isOn: false,
    year: "2020",
  },
  {
    id: 6,
    image: "",
    alt: "The National YoungArts Foundation & Independent Curators International (ICI)",
    descrip: "do it (home), Miami - Curated by Hans Ulrich Obrist",
    isOn: false,
  },
  {
    id: 7,
    image: "",
    alt: "International Center of Photography",
    descrip: "Artist Talk, New York City",
    isOn: false,
  },
  {
    id: 8,
    image: "",
    alt: "Serving The People",
    descrip:
      "STP Yard Sale, Nationwide, Curated by Lumia Nocito - Ideated and curated during covid. Proceeds donated to the Loveland Foundation",
    isOn: false,
  },
  {
    id: 9,
    image: "",
    alt: "Serving The People",
    descrip: "STP BFA Show, New York City",
    isOn: false,
  },
  {
    id: 10,
    image: "",
    alt: "The Cooper Union",
    descrip: "End of Year Show, New York City",
    isOn: false,
  },
  {
    id: 11,
    image: "",
    alt: "Art Basel",
    descrip: "Breaking Barriers, Miami",
    isOn: false,
    year: "2019",
  },
  {
    id: 12,
    image: "",
    alt: "The Cooper Union",
    descrip: "Hello World Group Climate Zine, New York City",
    isOn: false,
  },
  {
    id: 13,
    image: "",
    alt: "The Cooper Union",
    descrip: "End of Year Show, New York City",
    isOn: false,
  },
  {
    id: 14,
    image: "",
    alt: "MAMA & Art Baby Gallery",
    descrip: "Wallpaper, Netherlands",
    isOn: false,
    year: "2018",
  },
  {
    id: 15,
    image: "",
    alt: "Ken Allen Studios",
    descrip: "Spring, New York City",
    isOn: false,
    year: "2017",
  },
  {
    id: 16,
    image: "",
    alt: "The National YoungArts Foundation",
    descrip: "YoungArts Jewelbox, Miami",
    isOn: false,
    year: "2016",
  },
  {
    id: 17,
    image: "",
    alt: "The Metropolitan Museum of Art",
    descrip: "Scholastic Art and Writing Regional Exhibition, New York City",
    isOn: false,
    year: "2015",
  },
];



export { ExhData };
