const Images = {
  imageOne: require("../../images/Portfolio-01.webp"),
  imageTwo: require("../../images/Portfolio-02.webp"),
  imageThree: require("../../images/Portfolio-03.webp"),
  imageFour: require("../../images/Portfolio-04.webp"),
  imageFive: require("../../images/Portfolio-05.webp"),
  imageSix: require("../../images/Portfolio-06.webp"),
  imageSeven: require("../../images/Portfolio-07.webp"),
  imageEight: require("../../images/Portfolio-08.webp"),
  imageNine: require("../../images/Portfolio-09.webp"),
  imageTen: require("../../images/Portfolio-10.webp"),
  imageEleven: require("../../images/Portfolio-11.webp"),
  imageTwelve: require("../../images/Portfolio-12.webp"),
  imageThirteen: require("../../images/Portfolio-13.webp"),
  imageFourteen: require("../../images/Portfolio-14.webp"),
  imageFifteen: require("../../images/Portfolio-15.webp"),
  imageSixteen: require("../../images/Portfolio-16.webp"),
  imageSeventeen: require("../../images/Portfolio-17.webp"),
  imageEighteen: require("../../images/Portfolio-18.webp"),
  imageNineteen: require("../../images/Portfolio-19.webp"),
  imageTwenty: require("../../images/Portfolio-20.webp"),
  imageTwentyone: require("../../images/Portfolio-21.webp"),
};

const Data = [
  {
    id: 1,
    image: Images.imageOne,
    descrip: "Interview Magazine x Camper Lab Campaign",
    isOn: true,
  },
  {
    id: 2,
    image: Images.imageTwo,
    descrip: "",
    isOn: false,
  },
  {
    id: 3,
    image: Images.imageThree,
    descrip: "Coveteur",
    isOn: false,
  },
  {
    id: 4,
    image: Images.imageFour,
    descrip: "",
    isOn: false,
  },
  {
    id: 5,
    image: Images.imageFive,
    descrip: "Interview Magazine x Camper Lab Campaign",
    isOn: false,
  },
  {
    id: 6,
    image: Images.imageSix,
    descrip: "Miaou Spring Campaign ‘21",
    isOn: false,
  },
  {
    id: 7,
    image: Images.imageSeven,
    descrip: "Interview Magazine x Camper Lab Campaign",
    isOn: false,
  },
  {
    id: 8,
    image: Images.imageEight,
    descrip: "Nike Campaign",
    isOn: false,
  },
  {
    id: 9,
    image: Images.imageNine,
    descrip: "Elisa Johnson",
    isOn: false,
  },
  {
    id: 10,
    image: Images.imageTen,
    descrip: "Coveteur",
    isOn: false,
  },
  {
    id: 11,
    image: Images.imageEleven,
    descrip: "Nylon Japan",
    isOn: false,
  },
  {
    id: 12,
    image: Images.imageTwelve,
    descrip: "Mission Statement Magazine",
    isOn: false,
  },
  {
    id: 13,
    image: Images.imageThirteen,
    descrip: "Miaou Spring Campaign ‘21",
    isOn: false,
  },
  {
    id: 14,
    image: Images.imageFourteen,
    descrip: "Nylon Japan",
    isOn: false,
  },
  {
    id: 15,
    image: Images.imageFifteen,
    descrip: "",
    isOn: false,
  },
  {
    id: 16,
    image: Images.imageSixteen,
    descrip: "Interview Magazine x Camper Lab Campaign",
    isOn: false,
  },
  {
    id: 17,
    image: Images.imageSeventeen,
    descrip: "",
    isOn: false,
  },
  {
    id: 18,
    image: Images.imageEighteen,
    descrip: "Nike Campaign",
    isOn: false,
  },
  {
    id: 19,
    image: Images.imageNineteen,
    descrip: "",
    isOn: false,
  },
  {
    id: 20,
    image: Images.imageTwenty,
    descrip: "",
    isOn: false,
  },
  {
    id: 21,
    image: Images.imageTwentyone,
    descrip: "Mission Statement Magazine",
    isOn: false,
  },
];

export { Images, Data };
