const FeaData = [
  {
    id: 0,
    image: "",
    alt: "The Impression",
    descrip: "Coach Spring 2023 Fashion Show Front Row (Web)",
    isOn: true,
    year: "2022",
  },
  {
    id: 1,
    image: "",
    alt: "The Impression",
    descrip: "New York Street Style Spring 2023",
    isOn: true,
  },
  {
    id: 2,
    image: "",
    alt: "GQ",
    descrip: "The Next Wave of New York Fashion Week Stars Is Here (Web)",
    isOn: true,
  },
  {
    id: 3,
    image: "",
    alt: "V Magazine",
    descrip: "Miu Miu Serves Looks at The West Side Tennis Club (Web)",
    isOn: true,
  },
  {
    id: 4,
    image: "",
    alt: "Vogue",
    descrip:
      "Bella Hadid, Jen Batchelor, and Selby Drummond Fete Bumble x Kin Euphorics’ Latest Launch in Montauk (Web)",
    isOn: true,
  },
  {
    id: 5,
    image: "",
    alt: "The Impression",
    descrip:
      "Miu Miu Celebrated Its Fall 2022 Collection with a Tennis Club Takeover (Web)",
    isOn: false,
  },
  {
    id: 6,
    image: "",
    alt: "V Magazine",
    descrip: "Miu Miu Serves Looks at the West Side Tennis Club",
    isOn: false,
  },
  {
    id: 7,
    image: "",
    alt: "dsection Magazine",
    descrip: "Sharing Voices (Print)",
    isOn: true,
    year: "2021",
  },
  {
    id: 8,
    image: "",
    alt: "Nylon Japan",
    descrip: "City Girls (Print)",
    isOn: false,
  },
  {
    id: 9,
    image: "",
    alt: "Fashionography",
    descrip: "Lumia Nocito for The Fashionography (Web)",
    isOn: false,
  },
  {
    id: 10,
    image: "",
    alt: "TimeOut",
    descrip: "Six must-see public art installations of Art Basel 2021 (Web)",
    isOn: false,
  },
  {
    id: 11,
    image: "",
    alt: "The Daily Front Row",
    descrip:
      "Daily Events Diary: A Diamond-Filled Dinner in London, Supermodels Step Out, And More! (Web)",
    isOn: false,
  },
  {
    id: 11,
    image: "",
    alt: "Haute Living",
    descrip:
      "Haute Living’s Official Guide to Art Basel Miami Beach 2021 (Web)",
    isOn: false,
  },
  {
    id: 12,
    image: "",
    alt: "Purple Fashion Magazine",
    descrip: `“Daisies,” an Exhibition Curated by Paige Silver at The Standard, Miami (Web)`,
    isOn: false,
  },
  {
    id: 13,
    image: "",
    alt: "Cosmopolitan",
    descrip:
      "10 Spring Hair Trends That Are Going to Be All Over Your Feed (Web)",
    isOn: false,
  },
  {
    id: 14,
    image: "",
    alt: "Vogue Hong Kong",
    descrip: "Burberry FW21 (Web)",
    isOn: false,
  },
  {
    id: 15,
    image: "",
    alt: "About Face Beauty",
    descrip: "About Face Beauty x Dickies (Web)",
    isOn: false,
  },
  {
    id: 16,
    image: "",
    alt: "i-D Magazine",
    descrip: "5 Asian Americans on Disrupting the Creative Industries (Web)",
    isOn: false,
  },
  {
    id: 17,
    image: "",
    alt: "Office Magazine",
    descrip: "Artifact (Web)",
    isOn: false,
  },
  {
    id: 18,
    image: "",
    alt: "Allure",
    descrip: "Glitter is Good (Print)",
    isOn: false,
    year: "2020",
  },
  {
    id: 19,
    image: "",
    alt: "dsection Magazine",
    descrip: "Amalie Gassmann for dsection (Print)",
    isOn: false,
  },
  {
    id: 20,
    image: "",
    alt: "i-D Magazine",
    descrip: "There’s no place like Café Forgot (Web)",
    isOn: false,
  },
  {
    id: 21,
    image: "",
    alt: "Models.com",
    descrip: "F/W 2020 Show Package (Women) (Web)",
    isOn: false,
  },
  {
    id: 22,
    image: "",
    alt: "The Quarantine Diares",
    descrip: "Scan Me (Web)",
    isOn: false,
  },
  {
    id: 23,
    image: "",
    alt: "Office Magazine",
    descrip: "Kim Shui F/W ’20 (Web)",
    isOn: false,
  },
  {
    id: 24,
    image: "",
    alt: "WWD",
    descrip: "Backstage at Kim Shui RTW Fall 2020 (Web)",
    isOn: false,
  },
  {
    id: 25,
    image: "",
    alt: "Vogue Runway",
    descrip: "Kim Shui Fall 2020 (Web)",
    isOn: false,
  },
  {
    id: 26,
    image: "",
    alt: "All Saints",
    descrip: "How To Make a Face Mask (Web)",
    isOn: false,
  },
  {
    id: 27,
    image: "",
    alt: "Cosmopolitan",
    descrip: "The Millenial Sex Recession (Print)",
    isOn: false,
    year: "2019",
  },
  {
    id: 28,
    image: "",
    alt: "The Cut",
    descrip: "The Best Celebrity Party Looks of the Week (Web)",
    isOn: false,
  },
  {
    id: 29,
    image: "",
    alt: "The Cut",
    descrip: "Maripol Captures New York’s Next Generation (Web)",
    isOn: false,
  },
  {
    id: 30,
    image: "",
    alt: "i-D Magazine",
    descrip:
      "Meet the Designers Revolutionizing New York Fashion Week in 2019 (Web)",
    isOn: false,
  },
  {
    id: 31,
    image: "",
    alt: "Dazed",
    descrip:
      "NYC’s creative new gen unite to celebrate an iconic ASICS sneaker (Web)",
    isOn: false,
  },
  {
    id: 32,
    image: "",
    alt: "Good Morning America",
    descrip:
      "Lady Gaga's hairstylist shows us how to achieve 'hair goals' (Web)",
    isOn: false,
  },
  {
    id: 33,
    image: "",
    alt: "Vogue Runway",
    descrip: "Sandy Liang (Web)",
    isOn: false,
  },
  {
    id: 34,
    image: "",
    alt: "Cultured Mag",
    descrip:
      "Harlequins, Dreamy Landscapes & Small Details: More of our Favorites from the Runways (Web)",
    isOn: false,
  },
  {
    id: 35,
    image: "",
    alt: "A Magazine Curated by Simone Rocha",
    descrip: "Braiding Hair (Print)",
    isOn: false,
    year: "2018",
  },
  {
    id: 36,
    image: "",
    alt: "Airwalk",
    descrip: "Reinventing The Classics (Print)",
    isOn: false,
  },
  {
    id: 37,
    image: "",
    alt: "The Cut",
    descrip:
      "Out Of The Box - An 18-Year-Old Photographer Shoots the Fall Collections (Web)",
    isOn: false,
  },
  {
    id: 38,
    image: "",
    alt: "Hunger TV",
    descrip: "Braiding Hair (Web)",
    isOn: false,
  },
  {
    id: 39,
    image: "",
    alt: "Highsnobiety",
    descrip:
      "Watch the New Balance X90 Pay Homage to the Classic ‘90’s Sitcom (Web)",
    isOn: false,
  },
  {
    id: 40,
    image: "",
    alt: "Warpweb",
    descrip: "Manhattan Portage's 19SS latest LOOK is released! (Web)",
    isOn: false,
  },
  {
    id: 41,
    image: "",
    alt: "Hypebeast",
    descrip:
      "Manhattan Portage by photographer Peter Sutherland taken down Spring-summer 2019 lookbook book arrived (Web)",
    isOn: false,
  },
  {
    id: 42,
    image: "",
    alt: "Hypebae",
    descrip: `Opening Ceremony x Vans Cover the OG Slip-On LX in a "Floral Noir" Fuzz (Web)`,
    isOn: false,
  },
  {
    id: 43,
    image: "",
    alt: "Moose Knuckles",
    descrip: "October’s Sunshine Girl of The Month: Lumia Nocito (Web)",
    isOn: false,
  },
  {
    id: 44,
    image: "",
    alt: "Refinery29",
    descrip: "30 Instagram-Worthy Beauty Looks To Try This April (Web)",
    isOn: false,
  },
  {
    id: 45,
    image: "",
    alt: "W Magazine",
    descrip: "10 Ways to Wear Balmain’s Racy Military-Inspired Look (Web)",
    isOn: false,
    year: "2017",
  },
  {
    id: 46,
    image: "",
    alt: "W Magazine",
    descrip: "There’s No Wrong Way to Wear a Floral Dress (Web)",
    isOn: false,
  },
  {
    id: 47,
    image: "",
    alt: "Ray-Ban",
    descrip: "REMIX LifeCode Campaign (Web)",
    isOn: false,
  },
  {
    id: 48,
    image: "",
    alt: "Refinery29",
    descrip: "31 Perfect Looks To Copy This October (Web)",
    isOn: false,
  },
  {
    id: 49,
    image: "",
    alt: "Refinery29",
    descrip:
      "The Street Style Beauty Looks You'll Want To Wear Right Now (Web)",
    isOn: false,
  },
  {
    id: 50,
    image: "",
    alt: "Vogue Italia",
    descrip: `Petra Collins, "Gang" (Print)`,
    isOn: false,
    year: "2016",
  },
  {
    id: 51,
    image: "",
    alt: "The Cut",
    descrip:
      "Opening Ceremony Followed Its Funny Fashion Show With a Genuinely Fun Party (Web)",
    isOn: false,
  },
  {
    id: 52,
    image: "",
    alt: "W Magazine",
    descrip: "You’ll Want To Follow Everyone In The New Adidas Campaign  (Web)",
    isOn: false,
  },
  {
    id: 53,
    image: "",
    alt: "Flare Magazine",
    descrip: "10 Under-The-Radar Artsy Cool Kids You Need to Follow (Web)",
    isOn: false,
  },
];

export { FeaData };
