const Images = {
  imageOne: require("../../images/nylon.png"),
  imageTwo: require("../../images/nylon.png"),
  imageThree: require("../../images/nylon.png"),
};

const FeaData = [
  {
    id: 1,
    image: Images.imageOne,
    alt: "",
    descrip: "2016. description1",
    isOn: true,
  },
  {
    id: 2,
    image: Images.imageTwo,
    alt: "",
    descrip: "description2",
    isOn: false,
  },
  {
    id: 3,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 4,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 5,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 6,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 7,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 8,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 9,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 10,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 11,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 12,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 13,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 14,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 15,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 16,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 17,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 18,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 17,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 18,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 19,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 20,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 21,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 22,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 23,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 24,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 25,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 26,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 27,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 28,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 29,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 30,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 31,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 32,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 33,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 34,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
  {
    id: 35,
    image: Images.imageThree,
    alt: "",
    descrip: "description3",
    isOn: false,
  },
];

export { FeaData };
