const Images = {
  imageOne: require("../../images/nylon.png"),
  imageTwo: require("../../images/nylon.png"),
  imageThree: require("../../images/nylon.png"),
};

const HonData = [
  {
    id: 1,
    image: "",
    alt: "CFDA",
    descrip: "Member of 2021 CFDA Fashion Awards Guild",
    isOn: true,
    year: "2021",
  },
  {
    id: 2,
    image: "",
    alt: "The International Center of Photography",
    descrip: "Guest Artist, New York City",
    isOn: false,
  },
  {
    id: 3,
    image: "",
    alt: "Coveteur",
    descrip: "Artist in Residence",
    isOn: false,
  },
  {
    id: 4,
    image: "",
    alt: "The Cooper Union",
    descrip: "The A.A. Low Fund Prize for Excellence in Art, New York City",
    isOn: false,
  },
  {
    id: 5,
    image: "",
    alt: "The Cooper Union",
    descrip:
      "Vincent J. Mielcarek, Jr. (A’85) Memorial Fund Prize, New York City, Scholarship for Excellence in Photography",
    isOn: false,
    year: "2020",
  },
  {
    id: 6,
    image: "",
    alt: "The Cooper Union",
    descrip: "Irwin and Lillian Appel Endowment, New York City",
    isOn: false,
  },
  {
    id: 7,
    image: "",
    alt: "U.S. Presidential Scholar",
    descrip: "The Arts Nominee, Nationwide",
    isOn: false,
    year: "2017",
  },
  {
    id: 8,
    image: "",
    alt: "The National YoungArts Foundation",
    descrip: "Finalist Award, Nationwide",
    isOn: false,
    year: "2016",
  },
  {
    id: 9,
    image: "",
    alt: "Scholastic Art & Writing Awards Foundation",
    descrip: "1 Silver Key in Photography, Nationwide",
    isOn: false,
  },
  {
    id: 10,
    image: "",
    alt: "Scholastic Art & Writing Awards Foundation",
    descrip: "5 Honorable Mentions in Photography, Nationwide",
    isOn: false,
  },
  {
    id: 11,
    image: "",
    alt: "Scholastic Art & Writing Awards Foundation",
    descrip: "3 Gold Keys in Photography, Nationwide",
    isOn: false,
    year: "2015",
  },
  {
    id: 12,
    image: "",
    alt: "Scholastic Art & Writing Awards Foundation",
    descrip: "3 Silver Keys in Photography, Nationwide",
    isOn: false,
  },
  {
    id: 15,
    image: "",
    alt: "Scholastic Art & Writing Awards Foundation",
    descrip: "2 Honorable Mentions in Photography, Nationwide",
    isOn: false,
  },
  {
    id: 16,
    image: "",
    alt: "Scholastic Art & Writing Awards Foundation",
    descrip: "1 Gold Key in Photography, Nationwide",
    isOn: false,
  },
  {
    id: 17,
    image: "",
    alt: "Scholastic Art & Writing Awards Foundation",
    descrip: "2 Honorable Mentions in Photography, Nationwide",
    isOn: false,
    year: "2014",
  },
  {
    id: 18,
    image: "",
    alt: "Scholastic Art & Writing Awards Foundation",
    descrip: "3 Gold Keys in Photography, Nationwide",
    isOn: false,
    year: "2013",
  },
  {
    id: 19,
    image: "",
    alt: "Scholastic Art & Writing Awards Foundation",
    descrip: "2 Honorable Mentions in Photography, Nationwide",
    isOn: false,
  },
  //   {
  //     id: 9,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2016. 1 Silver Key in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 10,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2016. 1 Honorable Mention in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 11,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2016. 1 Honorable Mention in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 12,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2016. 1 Honorable Mention in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 13,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2016. 1 Honorable Mention in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 14,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2016. 1 Honorable Mention in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 15,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2015. 1 Gold Key in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 16,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2015. 1 Gold Key in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 17,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2015. 1 Gold Key in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 18,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2015. 1 Silver Key in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 19,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2015. 1 Silver Key in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 20,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2015. 1 Silver Key in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 21,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2015. 1 Honorable Mention in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 22,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2015. 1 Honorable Mention in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 23,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2014. 1 Gold Key in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 24,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2014. 1 Honorable Mention in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 25,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2014. 1 Honorable Mention in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 26,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2013. 1 Gold Key in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 27,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2013. 1 Gold Key in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 28,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2013. 1 Gold Key in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 29,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2013. 1 Honorable Mention in Photography, Nationwide",
  //     isOn: false,
  //   },
  //   {
  //     id: 30,
  //     image: "",
  //     alt: "Scholastic Art & Writing Awards Foundation",
  //     descrip: "2013. 1 Honorable Mention in Photography, Nationwide",
  //     isOn: false,
  //   },
];

export { HonData };
