const IntData = [
  {
    id: 1,
    image: "",
    alt: "The Fashionography",
    descrip: "Lumia Nocito for The Fashionography (Web)",
    isOn: true,
    year: "2021",
  },
  {
    id: 1,
    image: "",
    alt: "dsection Magazine",
    descrip: "Sharing Voices (Print)",
    isOn: true,
  },
  {
    id: 2,
    image: "",
    alt: "Nylon Japan",
    descrip: "City Girls (Print)",
    isOn: false,
  },
  {
    id: 3,
    image: "",
    alt: "Office Magazine",
    descrip: "Daisies 2021 (Web)",
    isOn: false,
  },
  {
    id: 4,
    image: "",
    alt: "i-D Magazine",
    descrip: "5 Asian Americans on Disrupting the Creative Industries (Web)",
    isOn: false,
  },
  {
    id: 5,
    image: "",
    alt: "Hypebeast China",
    descrip: "Monthly RWL (Web)",
    isOn: false,
  },
  {
    id: 6,
    image: "",
    alt: "PRZM",
    descrip: "Lumia Nocito, Reality Featured Through Her Lens (Web)",
    isOn: false,
  },
  {
    id: 7,
    image: "",
    alt: "Coveteur",
    descrip: "Endless Summer (Web)",
    isOn: false,
  },
  {
    id: 8,
    image: "",
    alt: "Dazed",
    descrip:
      "21 Photographers on Poignant Moments They Captured Before Lockdown (Web)",
    isOn: false,
    year: "2020",
  },
  {
    id: 9,
    image: "",
    alt: "The Know Culture",
    descrip: "Powerfully Groovy Lumia Nocito (Web)",
    isOn: false,
  },
  {
    id: 10,
    image: "",
    alt: "Serving The People",
    descrip: "Assigning Art an Actionable Function with Lumia Nocito (Web)",
    isOn: false,
  },
  {
    id: 11,
    image: "",
    alt: "New York Magazine’s The Strategist",
    descrip: "Converse Chuck 70’s vs. Air Force 1’s (Print)",
    isOn: false,
    year: "2019",
  },
  {
    id: 12,
    image: "",
    alt: "Nike",
    descrip: "Lumia Nocito: Balance (Web)",
    isOn: false,
  },
  {
    id: 13,
    image: "",
    alt: "Dazed",
    descrip:
      "Drama, drama, drama: watch No Agency’s models take an acting class (Web)",
    isOn: false,
  },
  {
    id: 14,
    image: "",
    alt: "Dazed Beauty",
    descrip:
      "Eight Unsigned Photographers Reimagine Masculinity through their Lens (Web)",
    isOn: false,
  },
  {
    id: 15,
    image: "",
    alt: "Milk Makeup",
    descrip: "Make Moves With Flex: Meet Lumia, Tatiana, and Ava (Web)",
    isOn: false,
  },
  {
    id: 16,
    image: "",
    alt: "Manual x The Standard",
    descrip: "Not Just a Disposable Camera (Web)",
    isOn: false,
  },
  {
    id: 17,
    image: "",
    alt: "La Garconne",
    descrip: "Chapter One (Web)",
    isOn: false,
  },
  {
    id: 18,
    image: "",
    alt: "Cools",
    descrip: "Lumia Nocito is the Future of Photography (Web)",
    isOn: false,
  },
  {
    id: 19,
    image: "",
    alt: "Melissa",
    descrip: "Hot Mess (Web)",
    isOn: false,
  },
  {
    id: 20,
    image: "",
    alt: "Nylon Japan",
    descrip: "What Makes You New? (Print)",
    isOn: false,
    year: "2018",
  },
  {
    id: 21,
    image: "",
    alt: "i-D Japan",
    descrip: "The Original Issue (Print)",
    isOn: false,
  },
  {
    id: 22,
    image: "",
    alt: "Notion Magazine",
    descrip: "24 Hours in NYC (Print)",
    isOn: false,
  },
  {
    id: 23,
    image: "",
    alt: "Melissa Galleria",
    descrip: "Boundless Expressions (Print)",
    isOn: false,
  },
  {
    id: 24,
    image: "",
    alt: "Refinery29",
    descrip: "Proof That You Can Be Successful As A Teenager (Web)",
    isOn: false,
  },
  {
    id: 25,
    image: "",
    alt: "Converse",
    descrip: "Spotted At 21 Mercer (Web)",
    isOn: false,
  },
  {
    id: 26,
    image: "",
    alt: "Milk",
    descrip: "The Next Generation of Authority On NYFW Street Style (Web)",
    isOn: false,
  },
  {
    id: 27,
    image: "",
    alt: "Vans by Opening Ceremony",
    descrip: "A New Generation of Masters (Web)",
    isOn: false,
  },
  {
    id: 28,
    image: "",
    alt: "DRØME Magazine Volume II",
    descrip: "Lumia Nocito (Print)",
    isOn: false,
    year: "2017",
  },
  {
    id: 29,
    image: "",
    alt: "Nordstrom",
    descrip:
      "Petra Collins Talks About Photographing Her Friends In Simone Rocha For Our Spring Campaign (Web)",
    isOn: false,
  },
  {
    id: 30,
    image: "",
    alt: "Refinery29",
    descrip:
      "The Rising Photographer Finally Stepping Out From Behind The Camera (Web)",
    isOn: false,
  },
  {
    id: 31,
    image: "",
    alt: "Refinery29 <20 Episode",
    descrip:
      "The Rising Photographer Finally Stepping Out From Behind the Camera (Web Series)",
    isOn: false,
  },
  {
    id: 32,
    image: "",
    alt: "Nu Mode Magazine",
    descrip: `"Visuals" Edition #16 The Spring Summer Issue, A Vision Behind A Craft (Print)`,
    isOn: false,
    year: "2016",
  },
  {
    id: 33,
    image: "",
    alt: "Adidas + UO",
    descrip: "We The Future Campaign (Worldwide, Print)",
    isOn: false,
  },
  {
    id: 34,
    image: "",
    alt: "i-D Magazine",
    descrip:
      "The Female Gaze Issue, Petra Collins’ Inspirational Women (Print)",
    isOn: false,
  },
  {
    id: 35,
    image: "",
    alt: "Bullett Magazine",
    descrip: "Meet The Homies of HSWLD (Web)",
    isOn: false,
  },
  {
    id: 36,
    image: "",
    alt: "The Fader",
    descrip: "Is Drake Actually Cool? (Web)",
    isOn: false,
  },
  {
    id: 37,
    image: "",
    alt: "Refinery29",
    descrip: "The Z List: This Is How New York Teens Actually Dress (Web)",
    isOn: false,
  },
  {
    id: 38,
    image: "",
    alt: "Urban Outfitters",
    descrip: "Lumia Nocito (Web)",
    isOn: false,
  },
];

export { IntData };
