const Images = {
  imageOne: require("./personal/PersonalPortfolio-01.jpg"),
  imageTwo: require("./personal/PersonalPortfolio-02.jpg"),
  imageThree: require("./personal/PersonalPortfolio-03.jpg"),
  imageFour: require("./personal/PersonalPortfolio-04.jpg"),
  imageFive: require("./personal/PersonalPortfolio-05.jpg"),
  imageSix: require("./personal/PersonalPortfolio-06.jpg"),
  imageSeven: require("./personal/PersonalPortfolio-07.jpg"),
  imageEight: require("./personal/PersonalPortfolio-08.jpg"),
  imageNine: require("./personal/PersonalPortfolio-09.jpg"),
  imageTen: require("./personal/PersonalPortfolio-10.jg"),
  imageEleven: require("./personal/PersonalPortfolio-11.jpg"),
  imageTwelve: require("./personal/PersonalPortfolio-12.jpg"),
  imageThirteen: require("./personal/PersonalPortfolio-13.jpg"),
  imageFourteen: require("./personal/PersonalPortfolio-14.jpg"),
  imageFifteen: require("./personal/PersonalPortfolio-15.jpg"),
  imageSixteen: require("./personal/PersonalPortfolio-16.jpg"),
  imageSeventeen: require("./personal/PersonalPortfolio-17.jpg"),
};

const Data = [
  {
    id: 1,
    image: Images.imageOne,
    descrip: "",
    isOn: true,
  },
  {
    id: 2,
    image: Images.imageTwo,
    descrip: "",
    isOn: false,
  },
  {
    id: 3,
    image: Images.imageThree,
    descrip: "",
    isOn: false,
  },
  {
    id: 4,
    image: Images.imageFour,
    descrip: "",
    isOn: false,
  },
  {
    id: 5,
    image: Images.imageFive,
    descrip: "",
    isOn: false,
  },
  {
    id: 6,
    image: Images.imageSix,
    descrip: "",
    isOn: false,
  },
  {
    id: 7,
    image: Images.imageSeven,
    descrip: "",
    isOn: false,
  },
  {
    id: 8,
    image: Images.imageEight,
    descrip: "",
    isOn: false,
  },
  {
    id: 9,
    image: Images.imageNine,
    descrip: "",
    isOn: false,
  },
  {
    id: 10,
    image: Images.imageTen,
    descrip: "",
    isOn: false,
  },
  {
    id: 11,
    image: Images.imageEleven,
    descrip: "",
    isOn: false,
  },
  {
    id: 12,
    image: Images.imageTwelve,
    descrip: "",
    isOn: false,
  },
  {
    id: 13,
    image: Images.imageThirteen,
    descrip: "",
    isOn: false,
  },
  {
    id: 14,
    image: Images.imageFourteen,
    descrip: "",
    isOn: false,
  },
  {
    id: 15,
    image: Images.imageFifteen,
    descrip: "",
    isOn: false,
  },
  {
    id: 16,
    image: Images.imageSixteen,
    descrip: "",
    isOn: false,
  },
  {
    id: 17,
    image: Images.imageSeventeen,
    descrip: "",
    isOn: false,
  },
];

export { Images, Data };
