const Images = {
  imageOne: require("./personal/PersonalPortfolio-01.png"),
  imageTwo: require("./personal/PersonalPortfolio-02.png"),
  imageThree: require("./personal/PersonalPortfolio-03.png"),
  imageFour: require("./personal/PersonalPortfolio-04.png"),
  imageFive: require("./personal/PersonalPortfolio-05.png"),
  imageSix: require("./personal/PersonalPortfolio-06.png"),
  imageSeven: require("./personal/PersonalPortfolio-07.png"),
  imageEight: require("./personal/PersonalPortfolio-08.png"),
  imageNine: require("./personal/PersonalPortfolio-09.png"),
  imageTen: require("./personal/PersonalPortfolio-10.jpeg"),
  imageEleven: require("./personal/PersonalPortfolio-11.png"),
  imageTwelve: require("./personal/PersonalPortfolio-12.png"),
  imageThirteen: require("./personal/PersonalPortfolio-13.png"),
  imageFourteen: require("./personal/PersonalPortfolio-14.png"),
  imageFifteen: require("./personal/PersonalPortfolio-15.png"),
  imageSixteen: require("./personal/PersonalPortfolio-16.png"),
  imageSeventeen: require("./personal/PersonalPortfolio-17.png"),
};

const Data = [
  {
    id: 1,
    image: Images.imageOne,
    descrip: "description1",
    isOn: true,
  },
  {
    id: 2,
    image: Images.imageTwo,
    descrip: "description2",
    isOn: false,
  },
  {
    id: 3,
    image: Images.imageThree,
    descrip: "description3",
    isOn: false,
  },
  {
    id: 4,
    image: Images.imageFour,
    descrip: "description2",
    isOn: false,
  },
  {
    id: 5,
    image: Images.imageFive,
    descrip: "description3",
    isOn: false,
  },
  {
    id: 6,
    image: Images.imageSix,
    descrip: "description2",
    isOn: false,
  },
  {
    id: 7,
    image: Images.imageSeven,
    descrip: "description3",
    isOn: false,
  },
  {
    id: 8,
    image: Images.imageEight,
    descrip: "description2",
    isOn: false,
  },
  {
    id: 9,
    image: Images.imageNine,
    descrip: "description3",
    isOn: false,
  },
  {
    id: 10,
    image: Images.imageTen,
    descrip: "description2",
    isOn: false,
  },
  {
    id: 11,
    image: Images.imageEleven,
    descrip: "description3",
    isOn: false,
  },
  {
    id: 12,
    image: Images.imageTwelve,
    descrip: "description2",
    isOn: false,
  },
  {
    id: 13,
    image: Images.imageThirteen,
    descrip: "description3",
    isOn: false,
  },
  {
    id: 14,
    image: Images.imageFourteen,
    descrip: "description2",
    isOn: false,
  },
  {
    id: 15,
    image: Images.imageFifteen,
    descrip: "description3",
    isOn: false,
  },
  {
    id: 16,
    image: Images.imageSixteen,
    descrip: "description2",
    isOn: false,
  },
  {
    id: 17,
    image: Images.imageSeventeen,
    descrip: "description3",
    isOn: false,
  },
];

export { Images, Data };
