const Images = {
  imageOne: require("./personal/PersonalPortfolio-01.webp"),
  imageTwo: require("./personal/PersonalPortfolio-02.webp"),
  imageThree: require("./personal/PersonalPortfolio-03.webp"),
  imageFour: require("./personal/PersonalPortfolio-04.webp"),
  imageFive: require("./personal/PersonalPortfolio-05.webp"),
  imageSix: require("./personal/PersonalPortfolio-06.webp"),
  imageSeven: require("./personal/PersonalPortfolio-07.webp"),
  imageEight: require("./personal/PersonalPortfolio-08.webp"),
  imageNine: require("./personal/PersonalPortfolio-09.webp"),
  imageTen: require("./personal/PersonalPortfolio-10.webp"),
  imageEleven: require("./personal/PersonalPortfolio-11.webp"),
  imageTwelve: require("./personal/PersonalPortfolio-12.webp"),
  imageThirteen: require("./personal/PersonalPortfolio-13.webp"),
  imageFourteen: require("./personal/PersonalPortfolio-14.webp"),
  imageFifteen: require("./personal/PersonalPortfolio-15.webp"),
  imageSixteen: require("./personal/PersonalPortfolio-16.webp"),
  imageSeventeen: require("./personal/PersonalPortfolio-17.webp"),
};

const Data = [
  {
    id: 1,
    image: Images.imageOne,
    descrip: "",
    isOn: true,
  },
  {
    id: 2,
    image: Images.imageTwo,
    descrip: "",
    isOn: false,
  },
  {
    id: 3,
    image: Images.imageThree,
    descrip: "",
    isOn: false,
  },
  {
    id: 4,
    image: Images.imageFour,
    descrip: "",
    isOn: false,
  },
  {
    id: 5,
    image: Images.imageFive,
    descrip: "",
    isOn: false,
  },
  {
    id: 6,
    image: Images.imageSix,
    descrip: "",
    isOn: false,
  },
  {
    id: 7,
    image: Images.imageSeven,
    descrip: "",
    isOn: false,
  },
  {
    id: 8,
    image: Images.imageEight,
    descrip: "",
    isOn: false,
  },
  {
    id: 9,
    image: Images.imageNine,
    descrip: "",
    isOn: false,
  },
  {
    id: 10,
    image: Images.imageTen,
    descrip: "",
    isOn: false,
  },
  {
    id: 11,
    image: Images.imageEleven,
    descrip: "",
    isOn: false,
  },
  {
    id: 12,
    image: Images.imageTwelve,
    descrip: "",
    isOn: false,
  },
  {
    id: 13,
    image: Images.imageThirteen,
    descrip: "",
    isOn: false,
  },
  {
    id: 14,
    image: Images.imageFourteen,
    descrip: "",
    isOn: false,
  },
  {
    id: 15,
    image: Images.imageFifteen,
    descrip: "",
    isOn: false,
  },
  {
    id: 16,
    image: Images.imageSixteen,
    descrip: "",
    isOn: false,
  },
  {
    id: 17,
    image: Images.imageSeventeen,
    descrip: "",
    isOn: false,
  },
];

export { Images, Data };
