const PhoData = [
  {
    id: 1,
    image: "",
    alt: "Interview Magazine",
    descrip:
      "Achilles Ion Gabriel Is Serving Up a Surreal SS22 Collection for CAMPERLAB",
    isOn: true,
    year: "2022",
  },
  {
    id: 2,
    image: "",
    alt: "Nylon Japan",
    descrip: "City Girls (Print)",
    isOn: false,
    year: "2021",
  },
  {
    id: 3,
    image: "",
    alt: "Mission Statement Magazine",
    descrip: "Chi Ossé for President (Print)",
    isOn: false,
  },
  {
    id: 4,
    image: "",
    alt: "Fletcher",
    descrip: "Girls Girls Girls (Single Cover)",
    isOn: false,
  },
  {
    id: 5,
    image: "",
    alt: "Nike",
    descrip: "New York Nature (Web)",
    isOn: false,
  },
  {
    id: 6,
    image: "",
    alt: "Nike",
    descrip: "New York City Treasure Hunt (Web)",
    isOn: false,
  },
  {
    id: 7,
    image: "",
    alt: "TMRW Magazine",
    descrip: "Connor Franta Shares His World (Web)",
    isOn: false,
  },
  {
    id: 8,
    image: "",
    alt: "Coveteur",
    descrip: "Endless Summer (Web)",
    isOn: false,
  },
  {
    id: 9,
    image: "",
    alt: "Dazed",
    descrip:
      "21 Photographers on Poignant Moments They Captured Before Lockdown (Web)",
    isOn: false,
    year: "2020",
  },
  {
    id: 10,
    image: "",
    alt: "Wonderland",
    descrip:
      "Brooklyn-Based Electro-pop Artist Evan Giia Premieres Sidelines (Web)",
    isOn: false,
  },
  {
    id: 11,
    image: "",
    alt: "E News",
    descrip:
      "Next-Gen Pop: The 15 Music Newcomers You Need to Know Before They Break Big (Web)",
    isOn: false,
  },
  {
    id: 12,
    image: "",
    alt: "All Saints",
    descrip: "Socials Shoot (Web)",
    isOn: false,
  },
  {
    id: 13,
    image: "",
    alt: "Bloomberg Businessweek",
    descrip:
      "The Clothing Brand for Preppies, Punks, and Bleeding-Heart Liberals (Print)",
    isOn: false,
    year: "2019",
  },
  {
    id: 14,
    image: "",
    alt: "Adidas x Concepts",
    descrip: "Adidas Ozweego (Print)",
    isOn: false,
  },
  {
    id: 15,
    image: "",
    alt: "Diesel",
    descrip: "Gabriel-Kane Day-Lewis (Print)",
    isOn: false,
  },
  {
    id: 16,
    image: "",
    alt: "Elle Mexico",
    descrip: "Elle Apuesta Por Tuza (Print)",
    isOn: false,
  },
  {
    id: 17,
    image: "",
    alt: "Nike",
    descrip: "Lumia Nocito: Balance (Web)",
    isOn: false,
  },
  {
    id: 18,
    image: "",
    alt: "Vogue",
    descrip:
      "Simone Rocha Hosts an Intimate Evening to Celebrate Her Louise Bourgeois Collaboration (Web)",
    isOn: false,
  },
  {
    id: 17,
    image: "",
    alt: "Wonderland",
    descrip: "Premiere: Evan Giia (Web)",
    isOn: false,
  },
  {
    id: 18,
    image: "",
    alt: "i-D Magazine",
    descrip:
      "This Photo Company Connects NYC Photographers, Artists, and Skaters Through Film (Web)",
    isOn: false,
  },
  {
    id: 19,
    image: "",
    alt: "Dazed Beauty",
    descrip:
      "Eight Unsigned Photographers Reimagine Masculinity through their Lens (Web)",
    isOn: false,
  },
  {
    id: 20,
    image: "",
    alt: "Cultured Magazine",
    descrip: "Tia Adeola Says The Ruff Is Back (Web)",
    isOn: false,
  },
  {
    id: 21,
    image: "",
    alt: "Cultured Magazine",
    descrip: "The Old School Meets The New With Sophia Wilson (Web)",
    isOn: false,
  },
  {
    id: 22,
    image: "",
    alt: "V Magazine",
    descrip: "Susan Alexandra Show was NYFW ‘19’s Most Fun (Web)",
    isOn: false,
  },
  {
    id: 23,
    image: "",
    alt: "Paper Magazine",
    descrip: "We're Here for Bagels and Drag Queens at Fashion Week (Web)",
    isOn: false,
  },
  {
    id: 24,
    image: "",
    alt: "Flaunt Magazine",
    descrip: "Simone Rocha for Hauser & Wirth Louise Bourgeois Earrings (Web)",
    isOn: false,
  },
  {
    id: 25,
    image: "",
    alt: "Felt USA",
    descrip: "F/W 2018 (Web)",
    isOn: false,
    year: "2018",
  },
  {
    id: 26,
    image: "",
    alt: "Converse",
    descrip: "Ant Blue Jr. (Print)",
    isOn: false,
  },
  {
    id: 27,
    image: "",
    alt: "Vogue",
    descrip: `“I Want People to Feel Connected”—Simone Rocha Constructs a Beautiful, Universal World (Web)`,
    isOn: false,
  },
  {
    id: 28,
    image: "",
    alt: "Oyster Magazine",
    descrip:
      "Slashed By Tia’s SS19 Campaign Has Got Us Dreamin’ Of A New York Summer (Web)",
    isOn: false,
  },
  {
    id: 29,
    image: "",
    alt: "Dazed",
    descrip:
      "The New Orleans native has starring roles in a score of 2018’s most exciting movies (Web)",
    isOn: false,
  },
  {
    id: 30,
    image: "",
    alt: "Glamour Magazine",
    descrip:
      "How Slashed by Tia Set a New Standard for Instagram Fashion Brands (Web)",
    isOn: false,
  },
  {
    id: 31,
    image: "",
    alt: "Garage Magazine",
    descrip: "Two Thumbs Up for All the Gloves at New York Fashion Week (Web)",
    isOn: false,
  },
  {
    id: 32,
    image: "",
    alt: "WWD",
    descrip:
      "If You Have Any Spare Time, Here’s Where To Chill Between Fashion Week Shows (Web)",
    isOn: false,
  },
  {
    id: 33,
    image: "",
    alt: "i-D Magazine",
    descrip:
      "Alice Longyu Gao is bringing Harajuku style to Times Square (Web)",
    isOn: false,
  },
  {
    id: 34,
    image: "",
    alt: "Paper Magazine",
    descrip: "Step into Alice Longyu Gao's Surreal World in New Pop-Up (Web)",
    isOn: false,
  },
  {
    id: 35,
    image: "",
    alt: "Complex",
    descrip:
      "Best Style Releases This Week: Supreme Box Logo Crewnecks, Bape Heads Show Tees, Fear of God Essentials Collection (Web)",
    isOn: false,
  },
  {
    id: 36,
    image: "",
    alt: "Sukeban Magazine",
    descrip: "Nowhere FC by Lumia Nocito (Web)",
    isOn: false,
  },
  {
    id: 37,
    image: "",
    alt: "Who What Wear",
    descrip: "It Girl, It Brand: Brigette Lundy-Paine and Collina Strada (Web)",
    isOn: false,
  },
  {
    id: 38,
    image: "",
    alt: "Heroine",
    descrip: "Slashed by Tia x Heroine (Web)",
    isOn: false,
  },
  {
    id: 39,
    image: "",
    alt: "Rag & Bone",
    descrip: "Nowhere FC (Web)",
    isOn: false,
  },
  {
    id: 40,
    image: "",
    alt: "DRØME Magazine Volume II",
    descrip: "Breaking Barriers (Cover Story, Print)",
    isOn: false,
    year: "2017",
  },
  {
    id: 41,
    image: "",
    alt: "Glamour Magazine",
    descrip: `10 Fashion Influencers on How They're Redefining "Sexy" (Print)`,
    isOn: false,
  },
  {
    id: 42,
    image: "",
    alt: "Womb Global",
    descrip:
      "We’ve Got Issues, I’ve Done Some Strange Things (Contributor, Print)",
    isOn: false,
  },
  {
    id: 43,
    image: "",
    alt: "Dazed",
    descrip:
      "Are we leveraging social media, or is social media leveraging us? (Web)",
    isOn: false,
  },
  {
    id: 44,
    image: "",
    alt: "WGSN",
    descrip:
      "Meet DRØME: the inclusive, independent publication making a big impact (Web)",
    isOn: false,
  },
  {
    id: 45,
    image: "",
    alt: "Galore Magazine",
    descrip:
      "How A Young Designer Got Rihanna To Rock Her Line After Just One Year (Web)",
    isOn: false,
  },
  {
    id: 46,
    image: "",
    alt: "Sukeban Magazine",
    descrip: "Unseen by Lumia Nocito (Web)",
    isOn: false,
  },
  {
    id: 47,
    image: "",
    alt: "Soccer Bible",
    descrip: "Nowhere FC Present the Football Concierge Test Lab (Web)",
    isOn: false,
  },
  {
    id: 48,
    image: "",
    alt: "Nu Mode Magazine",
    descrip: `"Visuals" Edition #16 The Spring Summer Issue, These Thoughts Behind Her Journal (Print)`,
    isOn: false,
    year: "2016",
  },
  {
    id: 49,
    image: "",
    alt: "Juxtapoz Magazine",
    descrip: "Lumia Nocito’s New York (Web)",
    isOn: false,
  },
  {
    id: 50,
    image: "",
    alt: "Milk",
    descrip: "What It’s Like To Get Painted By Beyonce’s Fave Artist (Web)",
    isOn: false,
  },
];

export { PhoData };
