const Images = {
  imageOne: require("./Portfolio-01.jpeg"),
  imageTwo: require("./Portfolio-02.jpeg"),
  imageThree: require("./Portfolio-03.jpeg"),
  imageFour: require("./Portfolio-04.jpeg"),
  imageFive: require("./Portfolio-05.jpeg"),
  imageSix: require("./Portfolio-06.jpeg"),
  imageSeven: require("./Portfolio-07.jpeg"),
  imageEight: require("./Portfolio-08.jpg"), 
  imageNine: require("./Portfolio-09.jpeg"),
  imageTen: require("./Portfolio-10.jpeg"), 
  imageEleven: require("./Portfolio-11.jpeg"),
  imageTwelve: require("./Portfolio-12.jpg"),
  imageThirteen: require("./Portfolio-13.jpeg"),
  imageFourteen: require("./Portfolio-14.jpeg"),
  imageFifteen: require("./Portfolio-15.jpeg"),
  imageSixteen: require("./Portfolio-16.jpeg"),
  imageSeventeen: require("./Portfolio-17.jpeg"),
  imageEighteen: require("./Portfolio-18.jpg"),
  imageNineteen: require("./Portfolio-19.jpg"),
  imageTwenty: require("./Portfolio-20.png"),
  imageTwentyone: require("./Portfolio-21.jpg"),
};

const Data = [
  {
    id: 1,
    image: Images.imageOne,
    descrip: "Interview Magazine x Camper Lab Campaign",
    isOn: true,
  },
  {
    id: 2,
    image: Images.imageTwo,
    descrip: "",
    isOn: false,
  },
  {
    id: 3,
    image: Images.imageThree,
    descrip: "Coveteur",
    isOn: false,
  },
  {
    id: 4,
    image: Images.imageFour,
    descrip: "",
    isOn: false,
  },
  {
    id: 5,
    image: Images.imageFive,
    descrip: "Interview Magazine x Camper Lab Campaign",
    isOn: false,
  },
  {
    id: 6,
    image: Images.imageSix,
    descrip: "Miaou Spring Campaign ‘21",
    isOn: false,
  },
  {
    id: 7,
    image: Images.imageSeven,
    descrip: "Interview Magazine x Camper Lab Campaign",
    isOn: false,
  },
  {
    id: 8,
    image: Images.imageEight,
    descrip: "Nike Campaign",
    isOn: false,
  },
  {
    id: 9,
    image: Images.imageNine,
    descrip: "Elisa Johnson",
    isOn: false,
  },
  {
    id: 10,
    image: Images.imageTen,
    descrip: "Coveteur",
    isOn: false,
  },
  {
    id: 11,
    image: Images.imageEleven,
    descrip: "Nylon Japan",
    isOn: false,
  },
  {
    id: 12,
    image: Images.imageTwelve,
    descrip: "Mission Statement Magazine",
    isOn: false,
  },
  {
    id: 13,
    image: Images.imageThirteen,
    descrip: "Miaou Spring Campaign ‘21",
    isOn: false,
  },
  {
    id: 14,
    image: Images.imageFourteen,
    descrip: "Nylon Japan",
    isOn: false,
  },
  {
    id: 15,
    image: Images.imageFifteen,
    descrip: "",
    isOn: false,
  },
  {
    id: 16,
    image: Images.imageSixteen,
    descrip: "Interview Magazine x Camper Lab Campaign",
    isOn: false,
  },
  {
    id: 17,
    image: Images.imageSeventeen,
    descrip: "",
    isOn: false,
  },
  {
    id: 18,
    image: Images.imageEighteen,
    descrip: "Nike Campaign",
    isOn: false,
  },
  {
    id: 19,
    image: Images.imageNineteen,
    descrip: "",
    isOn: false,
  },
  {
    id: 20,
    image: Images.imageTwenty,
    descrip: "",
    isOn: false,
  },
  {
    id: 21,
    image: Images.imageTwentyone,
    descrip: "Mission Statement Magazine",
    isOn: false,
  },
];

export {Images, Data};